name: rhymer
description: "Rhym making app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  cupertino_icons: ^1.0.2
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  realm: ^3.1.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.6.2
  flutter_launcher_icons: ^0.13.1
  build_runner:


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - .env

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"